config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks'}
  
  root to: 'application#welcome'

  get 'gifts/cheapest', to: 'gifts#cheap'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: 'login'
    get 'signup', to: 'devise/registrations#new', as: 'signup' 
  end

  resources :lists, only: [:index, :show] do
    resources :gifts, only: [:show, :new, :index, :edit]
  end

  resources :gifts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gift.rb
class Gift < ApplicationRecord
    
    scope :search_gifts, -> (giftname) { where("name LIKE ?", "%#{giftname}%") }
   
    belongs_to :user
    belongs_to :list

    accepts_nested_attributes_for :list

    validates :name, presence: true
    validates :store, presence: true
    validates :price, presence: true

end

app/models/list.rb
class List < ApplicationRecord
    has_many :gifts
    has_many :users, through: :gifts
    
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:omniauthable
    
    has_many :gifts
    has_many :lists, through: :gifts

    validates :username, presence: true, uniqueness: {case_sensitive: false }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.username = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0..20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def welcome
      if user_signed_in? 
        redirect_to lists_path
      end
    end

    def authentication 
        if !user_signed_in? 
          redirect_to '/'
        end 
    end 

end

    

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
     
    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
            sign_in_and_redirect @user
            flash[:notice] = "Congratulations, you're signed up!"
        else
            flash[:error] = 'There was a problem.'
            redirect_to new_user_registration_path
        end

        def failure
            flash[:error] = 'There was a problem'
            redirect_to new_user_registration_path        
        end
    end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
    before_action :authentication
    before_action :set_gift, only: [:show, :edit, :update, :destroy]

    def index
        #binding.pry
        if params[:q]
            @gifts = current_user.gifts.search_gifts(params[:q])
        else
            @gifts = current_user.gifts
        end
    end

    def new
        @gift = current_user.gifts.new(list_id: params[:list_id])
        #binding.pry
    end

    def create
        #binding.pry
        @gift = current_user.gifts.build(gift_params)
        #binding.pry
        if @gift.save
            redirect_to gift_path(@gift)
        else
            render :new
        end
    end

    def show
    end
    
    def edit
    end

    def update
        if @gift.update(gift_params)
            redirect_to gift_path(@gift)
        else
            render :edit
        end
    end

    def destroy
        @gift.destroy
        redirect_to list_path(@gift.list)
    end

    private

    def set_gift
        @gift = current_user.gifts.find_by(id: params[:id])
        if !@gift
            flash[:error]  = "I'm sorry, you don't have access to view that page."
            redirect_to gifts_path
        end
    end

    #strong params with keys, has many 
    def gift_params
        params.require(:gift).permit(
            :name,
            :store,
            :price,
            :comment,
            :list_id,
            list_attributes: [
                :name
            ]
        )
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :authentication

    def index
        if user_signed_in?
            @lists = current_user.lists.uniq
        else
            redirect_to '/'
        end
    end

    def show
        if user_signed_in?
            @list = current_user.lists.find_by(id: params[:id])
            if @list
                @gifts = current_user.gifts.where(list_id: params[:id])
                render :show
            else
                redirect_to lists_path
            end

        else
            redirect_to '/'
        end

    end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/application/welcome.html.erb
<div class="mx-auto" style="width: 300px;">
    <h1>Gift List Helper</h1>
</div>

    <% if user_signed_in?%>
<br>
<br>
<br>
    <div class="mx-auto" style="width: 200px;">
        <a class="btn btn-lg btn-outline-primary btn-block text-uppercase" href="/lists" role="button">View Gift Lists</a>
        <a class="btn btn-lg btn-outline-primary btn-block text-uppercase" href="/gifts/new" role="button">Create a Gift List</a>
    </div>
    <% else %>
    <br>
    <div class="mx-auto" style="width: 500px;">
        <h3><%= link_to "Sign Up", new_user_registration_path %> or
        <%= link_to "Login", new_user_session_path %> <br><br> to start being an organized gift giver!</h3>
    <% end %>
</div>

app/views/gifts/_form.html.erb
<%= form_for gift do|f| %>
    <div class="mx-auto" style="width: 400px;">
        <% if gift.list_id.nil? %>
        
            <h3>Create a New List:</h3>
    
        <%= f.fields_for :list, gift.build_list do |l| %> <br>
            <div class= "form-group">
                <%= l.label :Name %> <br>
                <%= l.text_field :name %>
            </div>
        <% end %>
    <br>
    <br>
    <div class="mx-auto" style="width: 200px;">
        <% else %>
            <%= f.hidden_field :list_id  %>
        <%end%>
        </div>
        <div class= "form-group">

            <%= f.label :Gift_Name %>
            <%= f.text_field :name, class: "form-control" %>
            <%= f.label :Store %>
            <%= f.text_field :store, class: "form-control" %>
            <%= f.label :Price %>
            <%= f.text_field :price, class: "form-control" %>
            <%= f.label :Comment %>
            <%= f.text_area :comment, class: "form-control" %>
        </div>
    
        <br>
        <%= f.submit gift.persisted? ? "Update Gift" : "Add Gift" %>
    </div>
<% end %>
    

app/views/gifts/edit.html.erb
<% if @gift.errors.full_messages.any? %>
    <% @gift.errors.full_messages.each do |error_message| %>
        <%= error_message if @gift.errors.full_messages.first == error_message %> <br />
    <% end %>
<% end %>
 
 
 <h1>Update Gift Information</h1>

 <%= render partial: "form", locals: {gift: @gift} %>

app/views/gifts/index.html.erb
<h1> Gift Results: </h1>

<% @gifts.each do |gift| %>

<h4><%= link_to gift.name, gift_path(gift) %> -- <%= gift.list.name %></h4>

<% end %>
<br>
<br>
    <button><%= link_to "My Lists", lists_path %></button>

app/views/gifts/new.html.erb
<br>
<br>
<body>
    <% if @gift.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@gift.errors.count, "error") %> prohibited this gift from being saved:</h2>
        <ul>
            <% @gift.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>


    <div class="mx-auto" style="width: 700px;">
        <h1>Create a New Gift List Or Add A Gift!</h1>
    </div>
<br>
<hr>
    <div class="mx-auto" style="width: 200px;">
        <%= render "form", gift: @gift %>
    </div>
</body>
<br>
<br>

app/views/gifts/show.html.erb
<br>
<br>
<table class="table table-bordered">
    <thead>
        <tr>
            <th> Gift </th>
            <th> Store </th>
            <th> Price </th>
            <th> Comments </th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td><%= @gift.name %></td>
            <td><%= @gift.store %></td>
            <td><%= @gift.price %></td>
            <td><%= @gift.comment %></td>

        </tr>
    </tbody>
</table>
<br>
<br>
<button><%= link_to "Edit Gift", edit_list_gift_path( @gift.list, @gift) %></button>
<button><%= link_to "Delete Gift", @gift, method: :delete, data: { confirm: 'Are you sure?' }%></button>
<button><%= link_to "Back", list_path(@gift.list) %></button>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Home</a>
    <div class="navbar-nav">
        <div class="form-inline">
        <% if !user_signed_in?%>
            <a class="nav-link" href="/signup">Signup </a>
            <a class="nav-link"href="/login">Login</a>
        <% else %>
            <a class="nav-item nav-link" href="/"> Welcome, <%= current_user.username %>  </a>
                
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% current_user.lists.uniq.each do |list| %>
                <a class="dropdown-item" href="/lists/<%= list.id %>"><%= list.name %></a>
                <%end%>
            </div>
            </li>
            <%= link_to 'Create a New Gift List', new_gift_path %>
            <%= link_to 'All Gifts', gifts_path %>


            <%= link_to "Logout", destroy_user_session_path, method: "delete", class: "nav-item nav-link" %><br>
        <% end%>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>GiftGuide Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="assets/stylesheets/application.css" />
    <link rel="stylesheet" href="assets/stylesheets/main.css" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/nav' %>
  </head>

  <body>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<br>
<h2>My Gift Lists</h2>
<hr>
    <div>
        <form  action="/gifts">
            <input  name="q" type="text" placeholder="Find a Gift">
            <button type="submit">Search</button>
        </form>
    </div>
<br>
<% @lists.each do |list| %>
<ul>
<h4><%= link_to list.name, list_path(list) %></h4>
</ul>
<% end %>
<br>
<br>
<button><%=  link_to "Create a Gift List", new_gift_path %></button>

app/views/lists/show.html.erb
<br>
<h2> Gift List for: <%= @list.name %> </h2>
<br>
<table class="table table-striped">
    <thead>
        <tr>
            <th> Gift </th>
        </tr>
    </thead>

    <tbody>
        <% @list.gifts.each do |g| %>
            <tr>
                <td><%= link_to g.name, list_gift_path(@list, g) %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<br>
<br>

    <p><%= link_to "Add a New Gift", new_list_gift_path(@list) %></p>

    <button><%= link_to "My Lists", lists_path %></button>